version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    # container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: simple_bank
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data  
  redis:
    image: redis:7-alpine
    # container_name: redis
  api:
    build:
      context: .
      dockerfile: Dockerfile
    # container_name: api
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - postgres
      - redis
    entrypoint:
      [
        "app/start.sh"
      ]
    command: ["/app/main"]
volumes:
  postgres-volume: